fix couldbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -23,7 +23,6 @@ steps:
       echo "***********************"
       echo "Branch: $BRANCH_NAME"
       echo "Commit SHA: $COMMIT_SHA"
-      echo "Revision ID: $REVISION_ID"
       echo "***********************"
 
 - id: 'tf init'
@@ -37,18 +36,10 @@ steps:
         terraform init -backend-config="bucket=$PROJECT_ID-tfstate" \
           -backend-config="prefix=env/$BRANCH_NAME"
       else
-        for dir in environments/*/
-        do
-          cd ${dir}
-          env=${dir%*/}
-          env=${env#*/}
-          echo ""
-          echo "*************** TERRAFORM INIT ******************"
-          echo "******* At environment: ${env} ********"
-          echo "*************************************************"
-          terraform init || exit 1
-          cd ../../
-        done
+        echo "***************************** FAIL INIT *******************************"
+        echo "environments/test does not exist."
+        echo "*******************************************************************************"
+        exit 1
       fi
 
 # [START tf-plan]
@@ -62,18 +53,10 @@ steps:
         cd environments/test
         terraform plan -var 'env=$BRANCH_NAME' -var 'project=$PROJECT_ID' -out=tf.plan
       else
-        for dir in environments/*/
-        do
-          cd ${dir}
-          env=${dir%*/}
-          env=${env#*/}
-          echo ""
-          echo "*************** TERRAFOM PLAN ******************"
-          echo "******* At environment: ${env} ********"
-          echo "*************************************************"
-          terraform plan || exit 1
-          cd ../../
-        done
+        echo "***************************** FAIL PLANNING *******************************"
+        echo "environments/test does not exist."
+        echo "*******************************************************************************"
+        exit 1
       fi
 # [END tf-plan]
 
@@ -142,7 +125,7 @@ steps:
       cd environments/test
       terraform destroy -auto-approve -var 'env=$BRANCH_NAME' -var 'project=$PROJECT_ID'
     else
-      echo "***************************** FAIL SHOWING *******************************"
+      echo "***************************** FAIL DESTROYING *******************************"
       echo "environments/test does not exist."
       echo "*******************************************************************************"
       exit 1
